server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microcompany_yaml  # Fixed the typo in "musql"
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver  # Updated to the correct driver class name
  application:
    name: Company
  
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


eureka:
  instance:
    prefer-ip-address: true
  client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
      defaultZone:  http://localhost:8084/eureka

