server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microcompany_yaml  # Fixed the typo in "musql"
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver  # Updated to the correct driver class name


  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
